language: node_js
node_js:
  - 0.8
  - 0.10
notifications:
  email:
    - jdemorais@linkedin.com
    - vbasavaraj@linkedin.com
    - jleppert@linkedin.com
    - jchan@linkedin.com
before_install:
  - npm install -g grunt-cli
