language: node_js
node_js:
  - "0.12"
  - "iojs"
matrix:
  include:
    - node_js: "0.10"
      env: TEST="all"
notifications:
  email:
    - jchan@linkedin.com
    - skinast@linkedin.com
before_install:
  - npm install -g npm
before_script:
  - npm update
sudo: false
cache:
  directories:
    - node_modules
